### PR TITLE
adding set builtin to safe_builtins list

### PR DESCRIPTION
**Pull request by ehfeng**
[Previous PR](https://github.com/zopefoundation/RestrictedPython/pull/41/files) accidentally removed set from the list.

If merged, can you also bump the version to 3.6.1?

### CODE REVIEW

**Comment by icemac** [comment]
@ehfeng Please rebase your PR to the current master so the tests are actually run on Travis-CI.

**Comment by ehfeng** [comment]
Rebased, but now tests are failing.

I'm starting realize this may be more involved than I originally though. I tried changing the [ZopeGuards](https://github.com/zopefoundation/AccessControl/blob/master/src/AccessControl/ZopeGuards.py) and adding a `GuardedSetType`, mimicking the `GuardDictType`, but I can't figure out how RestrictedPython pulls from [AccessControl](https://github.com/zopefoundation/AccessControl) (though I did find [this note](https://github.com/zopefoundation/RestrictedPython/blob/master/src/RestrictedPython/notes.txt) that seems to mention the `_safe_globals` that I need to add `set` to.)

Any direction would be really helpful.

**Comment by ehfeng** [comment]
Ok, I changed the tests for this to work, but I'm not sure if this was right.

**Comment by icemac** [comment]
@ehfeng The test you wrote does not use `safe_builtins` so your change in the test set-up does not tests that `set` is allowed. (Removing `set` from `safe_builtins` does not make the test failing.)
It seems there are currently no unit tests for `safe_builtins`. There is a [doctest](https://github.com/zopefoundation/RestrictedPython/blob/2d15393ab1957a9c12cc61bbe209f57e2a48bee8/src/RestrictedPython/README.txt#L124) which shows how to use `safe_builtins`. Your test should look a bit like this one to actually test that `set` is now a safe builtin.

**Comment by loechel** [comment]
@icemac could this pull request closed? after move to RestrictedPython 4 this is at least on the wrong branch to merge.

**Comment by icemac** [comment]
@ehfeng Since version 4.0a1 `set` is in [RestrictedPython.Utilities.utility_builtins](https://github.com/zopefoundation/RestrictedPython/blob/master/src/RestrictedPython/Utilities.py#L25). This PR is now obsolete, so I will close by now.

**Comment by ehfeng** [comment]
Damn, that's awesome. Sorry, been busy, didn't see this until now.

**Pull request closed without merging**
