### PR TITLE
Add Python 3.8 Walrus-Operator to working Expressions

### PR DESCRIPTION
**Pull request by loechel**

### CODE REVIEW

**Comment by icemac** [comment]
What are the security implications allowing this new operator?  (Compared with Ellipsis I see much more potential it could allow more than we want.)

**Comment by loechel** [comment]
I am still looking into all new Features of Python 3.8. And looking into new AST Modules that we do not have explicite covered in restricted Python. Walrus was just one of the first to look at.

For me the walrus operator is like a normal asign statement and must go through the same mechanics like a normal "=" so __getitem__, __setitem__, __getattr__, __setattr__  
We could check that and than decide to allow or deny, but we should have the visit_NamedExpr() in transformer.

**Comment by icemac** [comment]
@loechel Not having `visit_NamedExpr` means it is forbidden. So we can leave it out until we are sure that it behaves like a normal assignment.

**Comment by icemac** [comment]
Superseded by #195.

**Pull request closed without merging**
