### PR TITLE
Prepare final 3.11 supporting release.

### LINKED ISSUE #224: Support Python 3.11
Look through the change log of Python 3.11 (once the final version is released) for potential issues which need to be handled by RestrictedPython to prevent access to otherwise forbidden data/objects.

There is no need to support new language features of Python 3.11 right now, let's see how they evolve when started being used.

Open tasks:

- [X] make package installable and fix tests (#223)
- [X] cut an alpha dev release (5.3a1.dev0)
- [x] drop Python 2 support (and Python 3.5) for a sane Python 3.11 support (See #223 for details)
- [ ] look through the change log of the final Python 3.11.0 version for potential changes allowing to bypass restrictions #243

### PR DESCRIPTION
**Pull request by icemac**
I looked through the change log of the final Python 3.11.0 version for potential changes allowing to bypass restrictions: I did not find anything harmful.

Fixes #224.

Built using https://github.com/zopefoundation/meta/pull/164

### CODE REVIEW

**Review by ale-rt — APPROVED** [review]

**Review by loechel — APPROVED** [review]

**Comment by dataflake** [comment]
@icemac This is ready to merge, right?

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Comment by dataflake** [comment]
@icemac @loechel Is there anything blocking the release of version 6 now? I volunteer to do that. I would like one for a new Zope 5 that could then finally declare full support for Python 3.11, and a new Zope 5 is needed for the first Plone 6 release candidate.

The two outstanding PRs (change to error template creation and change how coverage reports are run on GHA) are not critical.

**Comment by icemac** [comment]
All outstanding blocker PRs are merged. I am now cutting a release.

**Comment by icemac** [comment]
I just released https://pypi.org/project/RestrictedPython/6.0/.

**Pull request merged**
