### PR TITLE
f-String instead of template

### PR DESCRIPTION
**Pull request by loechel**

### CODE REVIEW

**Comment by loechel** [comment]
At the moment it is just a prove that you can change the implementation to newer Python Version supporting syntax and enable use cases as described in #241

**Comment by eric-cpp** [comment]
Any ETA when this can be merged, please?

**Comment by dataflake** [comment]
I wonder if there are users that customized the template by monkey-patching that `syntax_error_template` variable itself, which would immediately break with this change. Or, in other words, the change as it is is backwards-incompatible. In all other packages we normally add a deprecation warning before just removing stuff.

**Comment by dataflake** [comment]
The OP has closed #241 because there is a workable solution that does not involve code changes on our end. I propose we close this PR.

**Pull request closed without merging**
